import {CityEngine} from '../3d/city-engine.js';
import {PLACES,CITY,distanceKm} from '../city-data/places.js';
import {placesProvider,routeProvider,copilotProvider,preferences,savedPlans} from '../services/providers.js';
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const html=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=name=>`<i data-lucide="${name}"></i>`;
const icons=()=>window.lucide?.createIcons();
const mobileQuery=window.matchMedia('(max-width: 650px)');
const mobile=()=>mobileQuery.matches;
const typeIcon=type=>({landmark:'building-2',cafe:'coffee',restaurant:'utensils',transit:'train-front',shopping:'shopping-bag',park:'trees',hospital:'cross',hotel:'bed-double',road:'waypoints',event:'calendar-days',construction:'construction'}[type]||'map-pin');
let selected=PLACES[0],engine,currentPlan=null,routes=[],routeIndex=0,timeTimer=null,toastTimer,searchTimer,searchGeneration=0,searchItems=[],queryBusy=false,routeBusy=false;
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
function openInspector(){ $('#inspector').hidden=false; $('#inspector').dataset.opened='true'; if(mobile()){ $('#inspector').classList.add('mobile-open');$('#layer-panel').classList.remove('mobile-open');$('#copilot').classList.add('collapsed');$('#copilot-collapse').setAttribute('aria-expanded','false');} }
function hideInspector(){$('#inspector').dataset.opened='false';if(mobile())$('#inspector').classList.remove('mobile-open');else $('#inspector').hidden=true;}
function renderPlace(place,{initial=false}={}){selected=place;$('#inspector').classList.remove('route-active');const curated=PLACES.some(p=>p.id===place.id);const demo=['event','construction'].includes(place.type);const nearby=PLACES.filter(p=>p.id!==place.id&&distanceKm(p.coordinates,place.coordinates)<1.5);const cafes=nearby.filter(p=>['cafe','restaurant'].includes(p.type)).length;const stations=nearby.filter(p=>p.type==='transit').length;const meters=Math.round(distanceKm(CITY.center,place.coordinates)*1000);const image=place.image?`<img src="${html(place.image)}" alt="Open-air dining plaza at DLF Cyber Hub"><span class="photo-caption">${icon('camera')} DLF Cyber Hub · reference photo</span>`:`<div class="generic-visual">${icon(typeIcon(place.type))}</div>`;
$('#inspector-content').innerHTML=`<div class="inspector-visual">${image}<span class="inspector-tag"><span class="status-dot"></span>${demo?'DEMO LOCATION':curated?'CURATED PLACE · STATIC':'OPENSTREETMAP DATA'}</span><button class="icon-button inspector-close" data-action="close-inspector" aria-label="Close location inspector">${icon('x')}</button></div><div class="inspector-body"><div class="inspector-title-row"><div><h2>${html(place.name)}</h2><div class="inspector-subtitle">${icon('map-pin')}${html(place.area)}</div></div><button class="icon-button" data-action="save-place" aria-label="Save this place">${icon('bookmark')}</button></div><span class="category-tag">${html(place.category)}</span><span class="location-distance">${meters<1000?meters+' m':(meters/1000).toFixed(1)+' km'} from city focus</span>${place.id==='cyberhub'||place.type==='road'?`<div class="inspector-metrics"><div class="metric"><span>${icon('car-front')} TRAFFIC</span><strong class="moderate">Moderate</strong><small>SIMULATED</small></div><div class="metric"><span>${icon('wind')} AIR QUALITY</span><strong class="good">86 <span style="font-size:7px;color:#889b9d">AQI</span></strong><small>SIMULATED</small></div><div class="metric"><span>${icon('sun')} WEATHER</span><strong data-weather-reading>${{clear:28,cloudy:25,rain:23,fog:20}[engine?.weather||'clear']}°C</strong><small>SIMULATED</small></div></div>`:`<p class="place-description">${html(place.description)}</p>${place.lines?`<p class="place-description">${icon('train-front')} ${html(place.lines)}<br><small>Services: static · arrivals: unavailable</small></p>`:''}<p class="coordinate-line">${place.coordinates[1].toFixed(5)}° N &nbsp; ${place.coordinates[0].toFixed(5)}° E</p>`}<div class="nearby-heading"><h3>IN THE NEIGHBORHOOD</h3><span>CURATED · WITHIN 1.5 KM</span></div><div class="nearby-list"><button data-action="nearby-food">${icon('utensils')}${cafes} dining spots</button><button data-action="nearby-transit">${icon('train-front')}${stations} stations</button></div><div class="insight-card"><h3>${icon('sparkles')} CITYPULSE INSIGHT</h3><p>${demo?'An illustrative scenario, not a verified city update.':place.type==='transit'?'Explore nearby places before your next connection. Current service times are unavailable.':place.id==='cyberhub'?'Coffee, a slow stroll, a great dinner. This corner of Cyber City puts it all within reach. <span style="color:#6f8996">Curated suggestion.</span>':'Real geography. A different perspective. Select a route to explore the roads around this location.'}</p></div><div class="inspector-actions"><button class="primary-button" data-action="route-place">${icon('route')}Get directions</button><button class="secondary-button" data-action="add-plan" aria-label="Add location to a plan">${icon('plus')} Plan</button></div><p class="inspector-footnote">${demo?'Demo data · not a real event or closure':'Approximate coordinates · opening hours unavailable'}</p></div>`;if(!initial)openInspector();icons();}
function setLayer(key,value,notify=false){const input=$(`[data-layer="${key}"]`);if(input)input.checked=value;engine?.toggleLayer(key,value);$('#active-layers').textContent=$$('[data-layer]:checked').length;$('#traffic-legend').hidden=!$('[data-layer="traffic"]').checked;if(notify&&value&&['weather','aqi','events','construction','crowd'].includes(key))toast(`${{weather:'Weather',aqi:'Air quality',events:'Events',construction:'Construction',crowd:'Crowd density'}[key]} layer uses ${['events','construction'].includes(key)?'demo':'simulated'} data.`);preferences.save({layers:Object.fromEntries($$('[data-layer]').map(i=>[i.dataset.layer,i.checked])),time:$('#time-slider').value});}
function renderRouteForm(destination=selected){openInspector();$('#inspector').classList.add('route-active');const from=destination.id==='cyberhub'?'phase2':'cyberhub';const items=PLACES.some(p=>p.id===destination.id)?PLACES:[...PLACES,destination];$('#inspector-content').innerHTML=`<header class="panel-heading"><div>${icon('route')}<h2>Plan a route</h2></div><button class="icon-button" data-action="close-inspector" aria-label="Close route planner">${icon('x')}</button></header><div class="inspector-body"><h2>A new perspective.</h2><p class="place-description">Find your way through the real road network.</p><form id="route-form" class="route-form"><label>STARTING POINT<select id="route-from">${items.map(p=>`<option value="${html(p.id)}" ${p.id===from?'selected':''}>${html(p.name)}</option>`).join('')}</select></label><label>DESTINATION<select id="route-to">${items.map(p=>`<option value="${html(p.id)}" ${p.id===destination.id?'selected':''}>${html(p.name)}</option>`).join('')}</select></label><button class="primary-button" type="submit">${icon('route')}Generate road route</button></form><p class="route-status">${icon('car-front')} Driving · OSRM / OpenStreetMap<br>Durations are estimated. Live traffic, turn restrictions in private complexes, and current road closures are not verified.</p><div id="route-result" aria-live="polite"></div></div>`;$('#route-form').addEventListener('submit',async e=>{e.preventDefault();const a=items.find(p=>p.id===$('#route-from').value),b=items.find(p=>p.id===$('#route-to').value);if(a.id===b.id){toast('Choose two different locations.');return;}await getRoute([a,b]);});icons();}
async function getRoute(stops,{plan=false}={}){if(routeBusy){toast('A route request is already in progress.');return;}routeBusy=true;const formButton=$('#route-form button[type="submit"]');if(formButton){formButton.disabled=true;formButton.textContent='Finding a road route…';}toast('Requesting actual road geometry…');try{routes=await routeProvider.route(stops);routeIndex=0;engine.drawRoute(routes[0]);if(plan){renderRouteForm(stops.at(-1));$('#route-from').value=stops[0].id;$('#route-to').value=stops.at(-1).id;}renderRouteResult();toast(routes[0].source.includes('STATIC')?'Cached OSM road route loaded · static snapshot, estimated duration.':'Route ready. Travel time is estimated, without live traffic.');}catch(error){const message=`Routing unavailable. ${error.message} No invented road route has been drawn.`;toast(message);if($('#route-result'))$('#route-result').innerHTML=`<p class="route-status">${html(message)}</p>`;}finally{routeBusy=false;if(formButton?.isConnected){formButton.disabled=false;formButton.innerHTML=icon('route')+'Generate road route';icons();}}}
function renderRouteResult(){const r=routes[routeIndex];if(!r||!$('#route-result'))return;$('#route-result').innerHTML=`<div class="route-summary"><div><strong>${r.duration} <small>min</small></strong><span>ESTIMATED DRIVE</span></div><div><strong>${r.distance.toFixed(1)} <small>km</small></strong><span>ROAD DISTANCE</span></div></div><p class="route-status">${html(r.source)} · real road geometry<br><span style="color:#c5b48c">Traffic overlay: simulated · not used in routing</span></p>${routes.length>1?`<button class="route-alternative" data-action="alternate-route">${icon('shuffle')} Show alternative ${routeIndex===0?'route':'primary route'} <span>${routes[(routeIndex+1)%routes.length].duration} min</span></button>`:'<p class="route-status">No alternative route returned by the provider.</p>'}<div class="inspector-actions"><button class="secondary-button" data-action="route-overview">${icon('scan')}Overview</button><button class="primary-button" data-action="follow-route">${icon('navigation')}Follow route</button></div><button class="assistant-action" data-action="clear-route">Clear route</button>`;icons();}
function renderPlan(plan){currentPlan=plan;openInspector();$('#inspector').classList.add('route-active');$('#inspector-content').innerHTML=`<header class="panel-heading"><div>${icon('sparkles')}<h2>Your city, your evening</h2></div><button class="icon-button" data-action="close-inspector" aria-label="Close itinerary">${icon('x')}</button></header><div class="inspector-body"><span class="eyebrow">DEMO ITINERARY</span><h2 style="margin-top:13px">Make time for a little more.</h2><p class="place-description">${html(plan.subtitle||'Your curated places, in the order you added them. Suggested stops—not live availability.')}</p><div class="itinerary">${plan.stops.map((s,i)=>`<article class="itinerary-stop"><span class="stop-number">${String(i+1).padStart(2,'0')}</span><div class="stop-content"><span>${html(s.label||s.place.category.toUpperCase())}</span><button data-stop="${i}">${html(s.place.name)}</button><small>${html(s.time||'Time not set')}</small></div></article>`).join('')}</div><p class="route-status">${html(plan.note||'Curated suggestions · opening hours and availability unverified')}</p><div class="itinerary-actions"><button class="primary-button" data-action="plan-route">${icon('route')}View road route</button><button class="secondary-button" data-action="start-plan">${icon('play')}Start tour</button></div><button class="assistant-action" data-action="save-plan">${icon('bookmark')}Save itinerary on this device</button><p class="inspector-footnote">Suggested times exclude an exact pedestrian route.</p></div>`;setLayer('restaurants',true);icons();}
let tourTimeouts=[];
function startPlan(){if(!currentPlan?.stops.length)return;tourTimeouts.forEach(clearTimeout);tourTimeouts=[];if(mobile())hideInspector();currentPlan.stops.forEach((s,i)=>{tourTimeouts.push(setTimeout(()=>{engine.flyTo(s.place.coordinates);toast(`${String(i+1).padStart(2,'0')} · ${s.place.name} · ${s.time||'Your next stop'}`);},i*3700));});toast('Starting your place-by-place camera tour.');}
async function askCopilot(text){if(queryBusy||!text.trim())return;queryBusy=true;$('#copilot').classList.remove('collapsed');$('#copilot-collapse').setAttribute('aria-expanded','true');$('#copilot').classList.add('has-response');$('#copilot-send').disabled=true;$('#copilot-input').value='';$('#copilot-response').innerHTML=`<h3>Connecting the dots<span class="loading-ellipsis">…</span></h3><p>Checking the demo city index.</p>`;try{const response=await copilotProvider.query(text);$('#copilot-response').innerHTML=`<h3>${response.kind==='plan'?html(response.message):'A little local knowledge.'}</h3><p>${html(response.kind==='plan'?response.subtitle:response.message)}</p>${response.kind==='plan'?'<button class="assistant-action" id="view-itinerary">Open your itinerary '+icon('arrow-up-right')+'</button>':''}`;if(response.kind==='plan'){renderPlan(response);engine.flyTo(response.stops[0].place.coordinates);$('#view-itinerary').addEventListener('click',()=>renderPlan(response));if(!mobile())$('#copilot').classList.remove('collapsed');}else if(response.kind==='place'){if(response.place.type==='cafe')setLayer('restaurants',true);engine.select(response.place);}else if(['traffic','weather','aqi','transit'].includes(response.kind)){setLayer(response.kind,true);if(response.kind==='weather')$('#environment-panel').hidden=false;if(response.kind==='transit')engine.overview();}icons();}catch(error){$('#copilot-response').innerHTML='<h3>Let’s try that again.</h3><p>The demo assistant could not complete this request. Search and city exploration are still available.</p>';console.warn('Demo copilot:',error.message);}finally{queryBusy=false;$('#copilot-send').disabled=false;}}
function dialog(title,content){$('#dialog-content').innerHTML=`<h2>${title}</h2>${content}`;if(!$('#app-dialog').open)$('#app-dialog').showModal();icons();}
function showDataInfo(){dialog('Real city. Honest data.',`<p>CityPulse is an interactive frontend demo of Gurugram. Geography is real; intelligence layers are clearly separated from observed data.</p><div class="data-source-row"><span>Roads, footprints & rail geometry</span><span>OPENSTREETMAP</span></div><div class="data-source-row"><span>Satellite imagery</span><span>ESRI / MAXAR · NOT LIVE</span></div><div class="data-source-row"><span>Curated place coordinates</span><span>STATIC · APPROXIMATE</span></div><div class="data-source-row"><span>Road routing</span><span>OSRM · ESTIMATED</span></div><div class="data-source-row sim"><span>Building heights & materials</span><span>OSM-DERIVED / ESTIMATED</span></div><div class="data-source-row sim"><span>Traffic, AQI, crowds & weather</span><span>SIMULATED</span></div><div class="data-source-row sim"><span>Events & construction</span><span>ILLUSTRATIVE DEMO</span></div><div class="data-source-row sim"><span>City Copilot</span><span>LOCAL INTENT PARSER</span></div><div class="data-source-row off"><span>Live AI, arrivals & opening hours</span><span>NOT CONNECTED</span></div><p class="dialog-note">Not a survey-grade or photorealistic twin. Footprint detail depends on OSM coverage; missing heights are estimated. No facade reconstruction, verified live city feeds, or server backend is included. Simulations must not be used for health, safety, or navigation decisions.</p><p>Mapping: © OpenStreetMap contributors · OpenFreeMap. Imagery: © Esri, Maxar, Earthstar Geographics. Reference photograph: LBB / DLF Cyber Hub.</p>`);}
function showHelp(){dialog('A city worth exploring.',`<p>Start at Cyber City, then follow your curiosity.</p><h3>Move around</h3><ul><li>Drag to pan. Scroll or pinch to zoom.</li><li>Right-drag (or Ctrl + drag) to rotate and tilt.</li><li>On touchscreens, rotate with two fingers.</li><li>Click a footprint, road, or place to inspect it.</li><li>Press <b>/</b> to search. Press <b>Esc</b> to close overlays.</li></ul><h3>Make it your city</h3><p>Toggle city layers, change the simulated time, and try rain or fog in Environment. Ask the demo copilot to plan an evening or find coffee. The Routes tab requests actual road geometry and supports a camera-follow preview.</p><p class="dialog-note">Map gestures cancel a route follow. Routes are estimated driving routes, not turn-by-turn navigation. Saved places and plans stay in this browser.</p>`);}
function showSaved(){const list=savedPlans.load();dialog('Your city, saved.',list.length?list.map((p,i)=>`<article class="saved-card"><h3>${html(p.name||'An evening in Gurugram')}</h3><p>${p.stops.map(s=>html(s.place.name)).join(' → ')}</p><button data-saved="${i}">Open itinerary ${icon('arrow-up-right')}</button></article>`).join(''):'<p>No saved plans yet.</p><p>Build an itinerary with City Copilot, or add a location using its Plan button, then choose “Save itinerary”. Plans are stored only on this device.</p>');$$('[data-saved]').forEach(button=>button.addEventListener('click',()=>{$('#app-dialog').close();renderPlan(list[Number(button.dataset.saved)]);}));icons();}
function setTime(value){let time=Number(value);if(time>=24)time=0;$('#time-slider').value=String(time);const hours=Math.floor(time),minutes=Math.round((time-hours)*60);$('#time-output').textContent=`${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}`;engine?.setTime(time);$$('.environment-options button').forEach(b=>b.classList.toggle('selected',time>=20||time<6?b.dataset.time==='22':time>=16?b.dataset.time==='17.5':b.dataset.time==='12'));}
function setWeather(weather) {
 engine.setWeather(weather);
 const scenes = {clear:['sun','28','Clear skies'],cloudy:['cloud','25','Cloudy'],rain:['cloud-rain','23','Rain'],fog:['cloud-fog','20','Fog']};
 const [symbol, temperature, label] = scenes[weather] || scenes.clear;
 const reading = $('[data-weather-reading]');
 if (reading) reading.textContent = temperature + '°C';
 $('#weather-button').innerHTML = `${icon(symbol)}<span><strong>${temperature}° <span>${label}</span></strong><small>WEATHER · SIMULATED</small></span>${icon('chevron-down')}`;
 icons();
}
function applyStartupParameters() {
 const params = new URLSearchParams(location.search);
 const hour = params.get('time');
 if (hour !== null && Number.isFinite(Number(hour)) && Number(hour) >= 0 && Number(hour) <= 24) setTime(Number(hour));
 const weather = params.get('weather');
 if (['clear','cloudy','rain','fog'].includes(weather)) { setLayer('weather',true); setWeather(weather); }
 const place = PLACES.find(p => p.id === params.get('place'));
 if (place) engine.select(place);
 if (params.get('view') === 'plan') askCopilot('Plan a 2 hour evening in Gurgaon. Avoid heavy traffic.');
 if (params.get('view') === 'route') renderRouteForm(place || PLACES[0]);
}
function escapeIntro(){ $('#intro').classList.add('complete'); }
function showMapError(message){$('#map-error-text').textContent=message;$('#map-error').hidden=false;$('#map-status').textContent='Map connection issue';escapeIntro();}
function boot(){icons();renderPlace(PLACES[0],{initial:true});engine=new CityEngine({onReady:()=>{$('#map-status').textContent='City connected';$('#map-error').hidden=true;setTimeout(escapeIntro,400);setTimeout(applyStartupParameters,2850);const pref=preferences.load();if(pref.time!==undefined)setTime(pref.time);if(pref.layers)Object.entries(pref.layers).forEach(([key,value])=>{if($(`[data-layer="${key}"]`))setLayer(key,!!value);});},onSelect:place=>renderPlace(place),onError:showMapError,onMove:(center,zoom)=>{$('#compass-button svg').style.transform=`rotate(${-engine.map.getBearing()}deg)`;}});setTimeout(escapeIntro,4200);
$('#skip-intro').addEventListener('click',escapeIntro);$('#retry-map').addEventListener('click',()=>location.reload());$('#dismiss-error').addEventListener('click',()=>$('#map-error').hidden=true);
$$('[data-layer]').forEach(input=>input.addEventListener('change',()=>setLayer(input.dataset.layer,input.checked,true)));
$('#reset-layers').addEventListener('click',()=>{$$('[data-layer]').forEach(input=>setLayer(input.dataset.layer,['buildings','roads','traffic'].includes(input.dataset.layer)));toast('City layers reset.');});
$('#collapse-layers').addEventListener('click',()=>{const open=$('#layer-content').hidden;$('#layer-content').hidden=!open;$('#collapse-layers').setAttribute('aria-expanded',String(open));$('#collapse-layers').innerHTML=icon(open?'minus':'plus');icons();});
$$('[data-view]').forEach(button=>button.addEventListener('click',()=>{$$('[data-view]').forEach(b=>b.classList.toggle('active',b===button));const view=button.dataset.view;if(view==='explore'){engine.overview();renderPlace(PLACES[0],{initial:mobile()});$('#layer-panel').classList.remove('mobile-open');if(mobile())hideInspector();}if(view==='layers'){$('#layer-content').hidden=false;$('#collapse-layers').setAttribute('aria-expanded','true');$('#layer-panel').classList.toggle('mobile-open');if(mobile())hideInspector();}if(view==='route')renderRouteForm();if(view==='saved')showSaved();}));
$('#inspector').addEventListener('click',async e=>{const stop=e.target.closest('[data-stop]');if(stop&&currentPlan){engine.flyTo(currentPlan.stops[Number(stop.dataset.stop)].place.coordinates);if(mobile())hideInspector();return;}const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;switch(a){case 'close-inspector':hideInspector();break;case 'route-place':renderRouteForm(selected);break;case 'nearby-food':setLayer('restaurants',true);toast('Showing curated dining locations. Opening hours are unavailable.');break;case 'nearby-transit':setLayer('transit',true);toast('Showing static metro stations and OSM rail geometry.');break;case 'save-place':try{savedPlans.add({name:selected.name,stops:[{place:selected,label:selected.category,time:'Time not set'}]});toast('Place saved on this device.');}catch{toast('Browser storage is unavailable.');}break;case 'add-plan':{const stops=currentPlan?.stops?[...currentPlan.stops]:[];if(!stops.some(s=>s.place.id===selected.id))stops.push({place:selected,label:selected.category,time:'Time not set'});renderPlan({name:'My Gurugram plan',stops});toast('Place added to your plan.');break;}case 'plan-route':if(currentPlan.stops.length<2){toast('Add at least two places to generate a route.');break;}await getRoute(currentPlan.stops.map(s=>s.place),{plan:true});break;case 'start-plan':startPlan();break;case 'save-plan':try{savedPlans.add(currentPlan);toast('Itinerary saved on this device.');}catch{toast('Browser storage is unavailable.');}break;case 'route-overview':engine.overview();break;case 'follow-route':if(engine.follow()){toast('Following your road route. Drag the map to stop.');if(mobile())hideInspector();}else toast('Generate a route first.');break;case 'alternate-route':routeIndex=(routeIndex+1)%routes.length;engine.drawRoute(routes[routeIndex]);renderRouteResult();break;case 'clear-route':engine.clearRoute();$('#route-result').innerHTML='';toast('Route cleared.');break;}});
$('#copilot-form').addEventListener('submit',e=>{e.preventDefault();askCopilot($('#copilot-input').value);});$$('[data-prompt]').forEach(b=>b.addEventListener('click',()=>askCopilot(b.dataset.prompt)));$('#copilot-collapse').addEventListener('click',()=>{const collapsed=$('#copilot').classList.toggle('collapsed');$('#copilot-collapse').setAttribute('aria-expanded',String(!collapsed));});
const showEnvironment=()=>$('#environment-panel').hidden=!$('#environment-panel').hidden;['weather-button','settings-button'].forEach(id=>$('#'+id).addEventListener('click',showEnvironment));$('#environment-close').addEventListener('click',()=>$('#environment-panel').hidden=true);$$('.environment-options [data-time]').forEach(b=>b.addEventListener('click',()=>setTime(b.dataset.time)));$$('.weather-options [data-weather]').forEach(b=>b.addEventListener('click',()=>{$$('.weather-options button').forEach(x=>x.classList.toggle('selected',x===b));setLayer('weather',true);setWeather(b.dataset.weather);toast(`${b.dataset.weather[0].toUpperCase()+b.dataset.weather.slice(1)} atmosphere · simulated`);}));$('#time-slider').addEventListener('input',e=>setTime(e.target.value));$('#time-slider').addEventListener('change',()=>preferences.save({layers:engine.layers,time:$('#time-slider').value}));$('#play-time').addEventListener('click',()=>{if(timeTimer){clearInterval(timeTimer);timeTimer=null;$('#play-time').innerHTML=icon('play');$('#play-time').setAttribute('aria-label','Animate time of day');}else{timeTimer=setInterval(()=>setTime((Number($('#time-slider').value)+.25)%24),600);$('#play-time').innerHTML=icon('pause');$('#play-time').setAttribute('aria-label','Pause time of day');}icons();});
$('#zoom-in').addEventListener('click',()=>engine.map?.zoomIn({duration:500}));$('#zoom-out').addEventListener('click',()=>engine.map?.zoomOut({duration:500}));$('#compass-button').addEventListener('click',()=>engine.map?.easeTo({bearing:0,duration:800}));$('#recenter-button').addEventListener('click',()=>engine.overview());$('#view-toggle').addEventListener('click',()=>{if(!engine.mapReady)return;const flat=engine.map.getPitch()>10;engine.map.easeTo({pitch:flat?0:61,bearing:flat?0:-26,duration:1100});$('#view-toggle').textContent=flat?'2D':'3D';});
['demo-info','notifications-button'].forEach(id=>$('#'+id).addEventListener('click',showDataInfo));$('#help-button').addEventListener('click',showHelp);$('#city-button').addEventListener('click',()=>dialog('One city. A deeper look.','<p>Gurugram, Haryana, India is the first CityPulse city. The geographic exploration area is limited to Gurugram and its immediate surroundings.</p><div class="data-source-row"><span>Gurugram</span><span>AVAILABLE NOW</span></div><div class="data-source-row off"><span>More cities</span><span>NOT YET AVAILABLE</span></div>'));$('#profile-button').addEventListener('click',()=>dialog('Your personal city space.','<p>You’re exploring in local demo mode. No account, sign-in, or server profile is connected.</p><p>Your layer preferences and saved itineraries are stored in this browser. Nothing is synced across devices.</p><button class="secondary-button" id="open-saved">View saved plans</button>')||$('#open-saved').addEventListener('click',showSaved));$('#dialog-close').addEventListener('click',()=>$('#app-dialog').close());$('#app-dialog').addEventListener('click',e=>{if(e.target===$('#app-dialog')){const r=$('#app-dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#app-dialog').close();}});
mobileQuery.addEventListener('change',()=>{if(mobile()&&$('#inspector').dataset.opened==='true')openInspector();});
setupSearch();document.addEventListener('keydown',e=>{const input=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);if(e.key==='/'&&!input){e.preventDefault();$('#search-input').focus();}if(e.key==='Escape'){$('#search-results').hidden=true;$('#search-input').setAttribute('aria-expanded','false');$('#environment-panel').hidden=true;$('#layer-panel').classList.remove('mobile-open');if(mobile())hideInspector();engine.stopFollowing();tourTimeouts.forEach(clearTimeout);}});window.addEventListener('offline',()=>showMapError('You are offline. Geographic tiles and road routing require an internet connection; the curated demo assistant still works.'));window.addEventListener('online',()=>{$('#map-error').hidden=true;toast('Connection restored.');});
window.CityPulse={engine,search:placesProvider.search,ask:askCopilot,route:getRoute,setLayer,setTime,places:PLACES};}
function renderSearch(items,status=''){searchItems=items;const panel=$('#search-results');panel.hidden=false;$('#search-input').setAttribute('aria-expanded','true');panel.innerHTML=items.map((p,i)=>`<button class="search-result" role="option" aria-selected="false" data-search-index="${i}">${icon(typeIcon(p.type))}<span><strong>${html(p.name)}</strong><small>${html(p.category)} · ${html(p.area)}</small></span></button>`).join('')+(status?`<div class="search-status">${html(status)}</div>`:'');$$('[data-search-index]').forEach(b=>b.addEventListener('click',()=>chooseSearch(Number(b.dataset.searchIndex))));icons();}
function chooseSearch(index){const p=searchItems[index];if(!p)return;$('#search-input').value=p.name;$('#search-results').hidden=true;$('#search-input').setAttribute('aria-expanded','false');engine.select(p);}
function setupSearch(){const input=$('#search-input');input.addEventListener('input',()=>{clearTimeout(searchTimer);const q=input.value.trim(),generation=++searchGeneration;if(!q){renderSearch(PLACES.slice(0,5),'CURATED PLACES · STATIC DATA');return;}const local=placesProvider.search(q);renderSearch(local,local.length?'CURATED CITY INDEX':'Searching OpenStreetMap…');if(!local.length&&q.length>2){searchTimer=setTimeout(async()=>{try{const results=await placesProvider.searchOSM(q);if(generation!==searchGeneration)return;renderSearch(results,results.length?'OPENSTREETMAP · VIA PHOTON':'No places found in Gurugram. Try “Cyber Hub” or “Sikanderpur”.');}catch{if(generation===searchGeneration)renderSearch([],'Online search is temporarily unavailable. Try Cyber Hub, Ambience Mall, or a curated metro station.');}},650);}});input.addEventListener('focus',()=>{if(!input.value.trim())renderSearch(PLACES.slice(0,5),'CURATED PLACES · STATIC DATA');});input.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();$('[data-search-index]')?.focus();}if(e.key==='Enter'){e.preventDefault();chooseSearch(0);}});$('#search-results').addEventListener('keydown',e=>{const buttons=$$('[data-search-index]');const index=buttons.indexOf(document.activeElement);if(e.key==='ArrowDown'){e.preventDefault();buttons[(index+1)%buttons.length]?.focus();}if(e.key==='ArrowUp'){e.preventDefault();if(index<=0)input.focus();else buttons[index-1]?.focus();}});document.addEventListener('click',e=>{if(!e.target.closest('.global-search')){$('#search-results').hidden=true;input.setAttribute('aria-expanded','false');}});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
